weather:
  rapid:
    api:
      key: 44abb26b40msh74f32c0c7d46dc1p170849jsn023d4ab03d08
      host: community-open-weather-map.p.rapidapi.com
      base:
        url: https://community-open-weather-map.p.rapidapi.com/

logging:
  file:
    path: "../../logs"
    

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
